### PR TITLE
Added Khalid Laouhi

### PR DESCRIPTION
**Pull request by khalidl**

### CODE REVIEW

**Comment by flexbox** [comment]
Hello @khalidl 
According to me you can proceed to merge :+1:

**Comment by khalidl** [comment]
Hi @flexbox
I’m not entirely sure how to merge this. I don’t see any option to do so.
Any help? 
Thanks!

**Comment by jdittrich** [comment]
I merged it.

**Comment by khalidl** [comment]
Great, thanks @jdittrich!

**Pull request merged**
